services:
  - type: web
    name: fastscan-platform
    env: node
    plan: free
    rootDir: .
    buildCommand: npm --prefix server install && npm --prefix client install && npm --prefix client run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
