import express from 'express';
import { db } from '../db.js';
import { v4 as uuidv4 } from 'uuid';
import { getIO, setWorkerStatusServer } from '../sockets/socketHandler.js';

const router = express.Router();

// Helper to find Level 1 Boss Worker for any worker
export function findMainWorker(workerId) {
  let curr = db.getUser(workerId);
  if (!curr || curr.role !== 'worker') return null;
  while (curr && curr.level > 1 && curr.parent_id) {
    const parent = db.getUser(curr.parent_id);
    if (!parent || parent.role !== 'worker') break;
    curr = parent;
  }
  return curr;
}

// Get worker profile & team hierarchy
router.get('/:id', (req, res) => {
  const worker = db.getUser(req.params.id);
  if (!worker || worker.role !== 'worker') {
    return res.status(404).json({ error: 'Worker not found' });
  }

  // Check if timeout has expired
  if (worker.timeout_until) {
    if (new Date(worker.timeout_until).getTime() <= Date.now()) {
      db.updateUser(worker.id, { timeout_until: null });
      worker.timeout_until = null;
    }
  }

  // Get subworkers directly or indirectly under this worker
  const allUsers = db.getUsers();
  const directSubworkers = allUsers.filter(u => u.parent_id === worker.id);
  const directIds = directSubworkers.map(s => s.id);
  const secondarySubworkers = allUsers.filter(u => directIds.includes(u.parent_id));
  const totalSubworkers = [...directSubworkers, ...secondarySubworkers];

  // Ensure worker has joining_key
  if (!worker.joining_key) {
    const existingKey = db.getKeys().find(k => k.used_by === worker.id || k.created_by === worker.id);
    worker.joining_key = existingKey ? existingKey.key : `KEY-${worker.id.toUpperCase()}`;
    db.updateUser(worker.id, { joining_key: worker.joining_key });
  }

  // Get keys generated by this worker
  const keys = db.getKeys().filter(k => k.created_by === worker.id);

  // Compute team completed stats
  const mainWorker = findMainWorker(worker.id);

  const dailyStats = db.getWorkerDailyStats(worker.id);

  res.json({
    worker,
    daily_stats: dailyStats,
    isLevel1: worker.level === 1,
    parent: worker.parent_id ? db.getUser(worker.parent_id) : null,
    subworkers: totalSubworkers,
    keys,
    mainWorkerId: mainWorker ? mainWorker.id : worker.id,
    mainWorkerName: mainWorker ? mainWorker.name : worker.name,
    canRequestPayout: worker.level === 1
  });
});

// Generate new invite key for subworker
router.post('/:id/generate-key', (req, res) => {
  const worker = db.getUser(req.params.id);
  if (!worker || worker.role !== 'worker') {
    return res.status(404).json({ error: 'Worker not found' });
  }

  // If worker is Level 3, they cannot spawn sub-workers beyond Level 3
  if (worker.level >= 3) {
    return res.status(400).json({ error: 'Level 3 workers cannot invite further sub-workers (Max depth reached).' });
  }

  const randomSuffix = Math.floor(1000 + Math.random() * 9000);
  const keyStr = `SUB-${worker.name.split(' ')[0].toUpperCase()}-${randomSuffix}`;

  const newKey = {
    key: keyStr,
    created_by: worker.id,
    created_by_name: worker.name,
    created_by_level: worker.level,
    target_level: worker.level + 1,
    created_at: new Date().toISOString(),
    used_by: null,
    status: 'active'
  };

  db.addKey(newKey);

  const io = getIO();
  if (io) io.emit('keys_updated', { workerId: worker.id });

  res.json({ message: 'Key generated successfully', key: newKey });
});

// Register / activate subworker using key
router.post('/register-subworker', (req, res) => {
  const { key, name } = req.body;
  if (!key || !name) {
    return res.status(400).json({ error: 'Key and worker name are required.' });
  }

  const keyRecord = db.getKey(key.trim().toUpperCase());
  if (!keyRecord) {
    return res.status(404).json({ error: 'Invalid invitation key.' });
  }
  if (keyRecord.status === 'used') {
    return res.status(400).json({ error: 'This invitation key has already been used.' });
  }

  const parent = db.getUser(keyRecord.created_by);
  if (!parent) {
    return res.status(400).json({ error: 'Parent referrer not found.' });
  }

  const newWorkerId = `worker_${name.toLowerCase().replace(/[^a-z0-9]/g, '_')}_${Date.now().toString().slice(-4)}`;
  const newWorker = {
    id: newWorkerId,
    role: 'worker',
    name: `${name} (Sub-worker L${keyRecord.target_level})`,
    level: keyRecord.target_level,
    parent_id: parent.id,
    balance: 0.00,
    consecutive_failures: 0,
    timeout_until: null,
    is_banned: false,
    total_personal_completed: 0,
    total_team_completed: 0
  };

  db.addUser(newWorker);
  db.updateKey(keyRecord.key, {
    used_by: newWorker.id,
    status: 'used',
    used_at: new Date().toISOString()
  });

  const io = getIO();
  if (io) io.emit('users_updated');

  res.json({ message: 'Sub-worker registered successfully!', worker: newWorker });
});

// Toggle worker Online / Offline status
router.post('/:id/toggle-status', (req, res) => {
  const { is_online } = req.body;
  const worker = db.getUser(req.params.id);
  if (!worker || worker.role !== 'worker') {
    return res.status(404).json({ error: 'Worker not found' });
  }

  const newStatus = !!is_online;
  setWorkerStatusServer(worker.id, newStatus);
  const updatedWorker = db.getUser(worker.id);

  res.json({
    message: `Worker status changed to ${newStatus ? 'ONLINE' : 'OFFLINE'}`,
    worker: updatedWorker,
    is_online: newStatus
  });
});

export default router;
